//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderitem
    {
        public int quantity { get; set; }
        public decimal price { get; set; }
        public int Order_id { get; set; }
        public int Item_id { get; set; }
    
        public virtual item item { get; set; }
        public virtual order order { get; set; }
    }
}
