//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class restaurantEntities : DbContext
    {
        public restaurantEntities()
            : base("name=restaurantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> account { get; set; }
        public virtual DbSet<accounttype> accounttype { get; set; }
        public virtual DbSet<item> item { get; set; }
        public virtual DbSet<itemtype> itemtype { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<orderitem> orderitem { get; set; }
        public virtual DbSet<table> table { get; set; }
    }
}
